#!/bin/bash
# Copyright (c) 2014, Alexander Krasnukhin <the.malkolm@gmail.com>

. "$(git boots --sh-setup)"

set -e

# a  - simple
# b: - with arg ($OPTARG)
while getopts "" flag; do
  case $flag in
    :|\?)
      usage
     ;;
  esac
done
shift $((OPTIND - 1))

: git merge --abort
: git cherry-pick --abort
: git rebase --abort
: git bisect reset

