#!/bin/bash -e

JIRA_REGEXP='[A-Z][A-Z]*-[0-9][0-9]*'

# TODO search for JIRA in the subject & body
rev_list="$@"
test -z "$rev_list" && rev_list=HEAD

sep="__SEP__"
git log --format="%h$sep%ae$sep%s$sep%d" $rev_list | while read line
do
  commit=$( echo $line | awk -F$sep '{print $1}')
  author=$( echo $line | awk -F$sep '{print $2}')
  subject=$(echo $line | awk -F$sep '{print $3}')
  refs=$(   echo $line | awk -F$sep '{print $4}')

  author=${author%%@*} # drop domain name
  subject=${subject//\'/} # drop quotes, they make bash crazy
  subject=${subject//\"/}

  jira=$(echo $subject | grep -o "$JIRA_REGEXP"; exit 0) # ok to fail
  if test -n "$jira"; then
    subject=$(echo $subject | awk "{ for(i=1; i<=NF; i++) if(\$i ~ /$jira/) {\$i=\"\"} {print}}") # clean from detected jira ref
  fi

  subject=$(echo $subject | sed '1 {
s/  */ /g      # remove all repeating spaces, who does  this?
s/^ *//        # remove leading spaces
s/ *$//        # remove trailing spaces
s/^[^:]*:  *// # strip off manually specified prefixes, people lie
s/^./\U&\E/    # capitalize first letter
s/\.$//        # remove dot, noise it is
}')

  # prefixes will have list of touched first level directories ordered by amount of changes
  prefixes=$(git diff $commit^! --dirstat=cumulative | sort -r | awk '{print $2}' | sed 's:/.*::' | cat -n | sort -ruk2 | awk '{print $2}' | sort -n | head -2)
  if test -n "$prefixes"; then
    prefixes=$(echo "["$prefixes"]")
  else
    : ${prefixes:="-"}
  fi

  author=$(  printf "%-16s\n" "$author")
  jira=$(    printf "%-10s\n" "$jira")
  prefixes=$(printf "%-16s\n" "$prefixes")

  black="\e[30m"
  red="\e[31m"
  green="\e[32m"
  yellow="\e[33m"
  blue="\e[34m"
  magenta="\e[35m"
  cyan="\e[36m"
  white="\e[37m"
  reset="\e[0m"

  perl -e "print \"$magenta$jira$reset $cyan$author$reset $cyan$prefixes$reset $yellow$commit$reset $subject $green$refs$reset\n\""
done | less -RFiK

