#!/bin/bash
# Copyright (c) 2012, Alexander Krasnukhin <the.malkolm@gmail.com>

sh_setup () {
    echo "$(dirname $(readlink -e $0))/git-utils"
}

clean () {
    sed -i 's/\t/    /g' "$@"
    sed -i 's/[ \t]*$//g' "$@"
}

copyright () {
    year="$(date +%Y)"
    author="$(git config --get user.name)"
    email="$(git config --get user.email)"
    sed -i -n "
1 {
# read extra line
    N
# check Copyright present
    s:Copyright:&:
# skip if so
    t skip
# print header
    P
# insert missing copyright
    i\
# Copyright (c) $year, $author <$email>
# delete header & next cycle
    D
    :skip
# print header & delete it
    P;D
}
1 ! {
    p
}
" "$@"
}

case "$1" in
    --sh-setup)
        shift
        sh_setup "$@"
        ;;
    --clean)
        shift
        clean "$@"
        ;;
    --copyright)
        shift
        copyright "$@"
        ;;
    *)
        error "Invalid argument"
        exit 1
esac
