#!/bin/bash
# Copyright (c) 2012, Alexander Krasnukhin <the.malkolm@gmail.com>

. "$(git boots --sh-setup)"

set -e

while getopts "n" flag; do
    case $flag in
        n)
            no_rebase="1"
            ;;
        :|\?)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

case $# in
    1)
        commit="$(git rev-parse -q --verify $1)"
        test -z "$commit" && die "invalid argument"
        ;;
    *)
        usage
        ;;
esac

# create fixup commit
git commit --fixup=$commit

if [ -n "$no_rebase" ]; then
  echo "Skipping rebase step."
  exit 0
fi

# stash if working tree is dirty
before=$(boots_stash_size)
git stash &>/dev/null
after=$(boots_stash_size)
if test $after -gt $before
then
    echo "Stashed your changes."
    stash="yes"
fi

# automatically apply fixup
GIT_EDITOR=":" git rebase --autosquash --interactive $commit^ || \
    if [ -z "$stash" ]; then
        die "Resolve conflicts."
    else
        die "Resolve conflicts and manually unstash your changes."
    fi

# pop from stash if stashed
test -n "$stash" && git stash pop
