#!/bin/bash
# Copyright (c) 2013, Alexander Krasnukhin <the.malkolm@gmail.com>

. "$(git boots --sh-setup)"

set -e

# # a  - simple
# # b: - with arg ($OPTARG)
# while getopts "" flag; do
#     case $flag in
#         :|\?)
#             usage
#             ;;
#     esac
# done
# shift $((OPTIND - 1))

delete_change_id () {
    git-sed -f '/Change-Id:/ d' "$@"
}

create_change_id() {
    git_dir="$(readlink -e $(git rev-parse --git-dir))"
    git filter-branch --msg-filter "
cat > $$
$git_dir/hooks/commit-msg $$
cat $$
rm $$
" "$@"
}

case "$1" in
    --delete-change-id)
        shift
        delete_change_id "$@"
        ;;
    --create-change-id)
        shift
        create_change_id "$@"
        ;;
    --recreate-change-id)
        shift
        delete_change_id "$@"
        create_change_id "$@"
        ;;
    *)
        usage
        ;;
esac
