#!/bin/sh
#
# TODO trash_clean = trash_bury, alias
# TODO trash_save is too complex, dig stash commits instead
# TODO better dig progress output (add subject?)
# TODO trash_show ~ git stash show
# TODO trash_drop ~ git stash drop
# TODO trash_branch ~ git stash branch
# TODO write help & usage
#

GIT_DIR="$(git rev-parse --git-dir)"
GIT_TRASH=
GIT_TRASH_DEFAULT="$GIT_DIR/.GIT_TRASH"

ref_trash="refs/heads/trash"

trap 'rm -f "$GIT_TRASH"' 0

function err {
    echo "$1" 1>&2
}

function die {
    err "$1"
    exit 1
}

# stash size
function stash_size {
    echo $(git stash list | wc -l)
}

# search for trash
function trash_search {
    test -z "$GIT_TRASH" &&
    GIT_TRASH="$GIT_TRASH_DEFAULT" &&
    git fsck --no-progress --unreachable | \
	awk '/commit/ {print $3}' | \
	git rev-list --reverse --stdin --no-walk --grep="^TRASH" HEAD -- | \
	sed "/$(git rev-parse HEAD)/ d" | \
	tee "$GIT_TRASH"
}

# bury trash back, does it smell?
function trash_bury {
    trash_have || return 0

    current=$(git show-ref -q --verify $ref_trash)
    git reflog expire --expire=now $ref_trash
    git update-ref -d $ref_trash $current
}

# dig for trash
function trash_dig {
    trash_search
    while read commit
    do
	subject="$(git log --no-walk --format='%s' $commit --)"
	git update-ref -m "$subject" $ref_trash $commit
    done < "$GIT_TRASH"
}

# check if trash exist
function trash_have {
    git show-ref -q --verify $ref_trash
}

# list recovered trash
function trash_list {
    trash_have || return 0

    git log --format="%h %gd: %gs" -g "$@" $ref_trash --
}

# apply trash commit
function trash_apply {
    git stash apply "$@"
}

# save to trash
function trash_save {
    # remember stash size before
    before=$(stash_size)

    # try to stash
    args=$(git rev-parse --sq-quote "$@")
    command="git stash save $args"
    eval "$command" >/dev/null || die "Failed to stash!"

    # remember stash size after
    after=$(stash_size)

    # stash size didn't change, nothing to trash
    test $after -eq $before && die "No local changes to trash!"

    # remember stash
    stash=$(git rev-parse refs/stash)

    # drop stash
    git stash drop &>/dev/null

    # detect stash's tree
    tree=$(git cat-file -p $stash | awk '/^tree/ {print $2; exit}')

    # detect stash's parents
    declare -a parents=($(git cat-file -p $stash | awk '/^parent/ {print $2}'))

    # create a new trash commit, use stash's message & parents
    trash=$(git log --no-walk --format=%B $stash -- | sed -n '
1 {
    s/^WIP on/TRASH on/
    s/^On/TRASH on/
    p
}
1 ! {
    p
}' | git commit-tree -p ${parents[0]} -p ${parents[1]} $tree)

    (test -z $trash || test "$(git cat-file -t $trash)" !=  "commit") && \
	err "Failed to trash!" && \
	git stash apply $stash

    echo "\
Trashed working directory and index state $(git log --no-walk --format=%s $trash -- ).
HEAD is now at $(git log --no-walk --format='%h %s' HEAD -- )"
}

set -e

test $# -eq 0 && set "save" "$@"

case "$1" in
    search)
	shift
	trash_search "$@"
	;;
    dig)
	shift
	trash_dig "$@"
	;;
    bury)
	shift
	trash_bury "$@"
	;;
    list)
	shift
	trash_list "$@"
	;;
    apply)
	shift
	trash_apply "$@"
	;;
    save)
	shift
	trash_save "$@"
	;;
    *)
	die "Invalid command!"
	;;
esac
