#!/bin/bash
# Copyright (c) 2012, Alexander Krasnukhin <the.malkolm@gmail.com>

. "$(git boots --sh-setup)"
require require_clean_work_tree

while getopts "fn" flag; do
    case $flag in
        f)
            git_force="-f"
            ;;
        n)
            sed_quiet="-n"
            ;;
        :|\?)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

require_clean_work_tree "execute $(basename $0)" "Commit or stash your changes and try again."

if [ $# -eq 0 ]; then
    usage
fi

sed_script="$1"
shift

rev_args="$@"

if test "$rev_args" = "-"
then
    rev_args=
    while read -r line
    do
        rev_args="$rev_args $line"
    done
# get rid off leading & trailing spaces
    rev_args="$(echo $rev_args)"
fi

test -z "$rev_args" && exit 0 # avoid empty rev-list options

git rev-parse $rev_args &>/dev/null ||
    die "ambiguous or invalid rev-list options: '$rev_args'"

git filter-branch $git_force --msg-filter "
    sed $sed_quiet -r '$sed_script'
" $rev_args
