#!/bin/bash

GIT_ALIASES=$(cat << EOF
append          commit --amend -C HEAD
last            log -n 1
index           diff --cached
incoming        log ...@{u}
outgoing        log @{u}...
new             log $1@{1}..$1@{0}
empty-tree-sha1 hash-object -t tree /dev/null
stash-unapply   git stash show -p | git apply -R
EOF
)

set -e

echo "$GIT_ALIASES" | \
    sed '/^[ \t]*(#|$)/ d' | \
    while read line;
do
    alias=$(echo "$line"   | awk '{print $1}')
    command=$(echo "$line" | awk '{print substr($0,index($0,$2))}')
    eval "git config --global alias.$alias \"$command\""
done
