#!/bin/bash
# Copyright (c) 2012, Alexander Krasnukhin <the.malkolm@gmail.com>
#
# TODO stash recovery doesn't work
#

. "$(git boots --sh-setup)"

set -e
set $(no_flags "$@")

case $# in
    1)
        commit="$(git rev-parse -q --verify $1)"
        test -z "$commit" && die "invalid argument"
        ;;
    *)
        usage
        ;;
esac

test -z "$commit" && usage

# create fixup commit
git commit --fixup=$commit

# stash if working tree is dirty
before=$(boots_stash_size)
git stash &>/dev/null
after=$(boots_stash_size)
if $after -gt $before
then
    echo "Stashed your changes."
    stash="yes"
fi

# automatically apply fixup
git rebase --autosquash --interactive $commit^ || \
    if [ -z "$stash" ]; then
        die "Resolve conflicts."
    else
        die "Resolve conflicts and manually unstash your changes."
    fi

# pop from stash if stashed
test -n "$stash" && git stash pop
